### ISSUE TITLE
Problem after clean install - cannot open port

### ISSUE THREAD

**Issue by JakubTHOC** [madchicken/homebridge-zigbee-nt#118]
Hi
At the beginning I would like to say that the same configuration/device was working before.

I've maid clean install of homebridge-zigbee-nt 2.0.5 version.
I have CC2531 USB connected
Now when I reboot my raspberry I get this message in Homebridge logs:

`[ZigBee] Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at Znp.<anonymous> (/usr/local/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:23:12)
    at SerialPort.<anonymous> (/usr/local/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:144:65)
    at SerialPort._error (/usr/local/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /usr/local/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12`

For me it seems that there is some problem with opening usb port where CC2531 dongle is connected.

I see that dongle is recognized by system:
`Bus 001 Device 002: ID 0451:16a8 Texas Instruments, Inc. `

Dongle is here:
`/dev/ttyACM0`

But when I list what process is using dongle I get nothing:
`lsof | grep /dev/ttyACM0`

Where to look for resolution?
Cheers 
Jakub

**Comment by madchicken** [comment]
Sorry to be late on this. This is something that the plugin does not control, since all the job of connecting to the dongle is done by the herdsman library (that is the same library zigbee2mqtt uses). When this happens, it usually means two things: there is another process using the dongle or there is a stuck process keeping the port open. When it happened to me, restarting the raspberry worked

**Comment by madchicken** [comment]
Close as stale
