### ISSUE TITLE
Web UI don't lunch 

### ISSUE THREAD

**Issue by piokacz** [madchicken/homebridge-zigbee-nt#131]
Hello @madchicken I did clean install of Your plugin - version 2.1, I cleared the accessories cache. The Web UI don't work on any port. I restart the raspberry and Homebridge few times - but it didn't help, also I don't see any error in logs. 
```
[3/1/2021, 9:53:02 PM] [ZigBee] Successfully started ZigBee service
[3/1/2021, 9:53:02 PM] [ZigBee] ZigBee platform initialized @ 0x00124b0014da2968
```

**Comment by madchicken** [comment]
@piokacz Can you try v2.1.2? I added some log to debug this issue

**Comment by piokacz** [comment]
Hello @madchicken , many thanks that your plugin works via homebridge interface - now I can install it without the need to buid it from the source. 

My version of plugin:
`
homebridge-zigbee-nt v2.1.2
`
my logs after homebridge restart:
```
[3/3/2021, 10:23:04 PM] [ZigBee] Successfully started ZigBee service
[3/3/2021, 10:23:04 PM] [ZigBee] ZigBee platform initialized @ 0x00124b0014da2968
[3/3/2021, 10:23:04 PM] [ZigBee] Reuse accessory from cache with uuid 6895c160-ba25-497f-b805-38071c751c56 and name zigbee:permit-join
[3/3/2021, 10:23:04 PM] [ZigBee] Zigbee: disabling joining new devices.
[3/3/2021, 10:23:04 PM] [ZigBee] PermitJoin accessory successfully registered
[3/3/2021, 10:23:04 PM] [ZigBee] Reuse accessory from cache with uuid 4994893c-ea77-4292-a4ad-09e1f36f7099 and name zigbee:touchlink
[3/3/2021, 10:23:04 PM] [ZigBee] TouchLink accessory successfully registered
[3/3/2021, 10:23:04 PM] [ZigBee] Initializing ZigBee device: 0x086bd7fffec995f1 - RH3040 - TUYATEC-e4wp7oyu
[3/3/2021, 10:23:04 PM] [ZigBee] Reuse accessory from cache with uuid 4d997f57-ab72-4b46-bab6-f4b58d1df573 and name 0x086bd7fffec995f1
[3/3/2021, 10:23:04 PM] [ZigBee] Successfully auto discovered device: 0x086bd7fffec995f1, PIR sensor
[3/3/2021, 10:23:04 PM] [ZigBee] Registered device: 0x086bd7fffec995f1 TUYATEC-e4wp7oyu RH3040
[3/3/2021, 10:23:04 PM] [ZigBee] Mounting device 0x086bd7fffec995f1...
[3/3/2021, 10:23:04 PM] [ZigBee] Initializing ZigBee device: 0xbc33acfffed7e1b2 - TRADFRI motion sensor - IKEA of Sweden
[3/3/2021, 10:23:04 PM] [ZigBee] Reuse accessory from cache with uuid c2745d52-7755-417b-afe7-8f89cd8f8fb7 and name 0xbc33acfffed7e1b2
[3/3/2021, 10:23:04 PM] [ZigBee] Found class for device with key IKEA of Sweden:TRADFRI motion sensor
[3/3/2021, 10:23:04 PM] [ZigBee] Registered device: 0xbc33acfffed7e1b2 IKEA of Sweden TRADFRI motion sensor
[3/3/2021, 10:23:04 PM] [ZigBee] Mounting device 0xbc33acfffed7e1b2...
[3/3/2021, 10:23:04 PM] [ZigBee] Initializing ZigBee device: 0x60a423fffe029b7b - RH3052 - TUYATEC-yg5dcbfu
[3/3/2021, 10:23:04 PM] [ZigBee] Reuse accessory from cache with uuid 848737fa-56a0-41bd-bc63-b2bec685cd05 and name 0x60a423fffe029b7b
[3/3/2021, 10:23:04 PM] [ZigBee] Successfully auto discovered device: 0x60a423fffe029b7b, Temperature & humidity sensor
[3/3/2021, 10:23:04 PM] [ZigBee] Registered device: 0x60a423fffe029b7b TUYATEC-yg5dcbfu RH3052
[3/3/2021, 10:23:04 PM] [ZigBee] Mounting device 0x60a423fffe029b7b...
[3/3/2021, 10:23:04 PM] [ZigBee] Initializing ZigBee device: 0x60a423fffe2cd0e5 - RH3052 - TUYATEC-yg5dcbfu
[3/3/2021, 10:23:04 PM] [ZigBee] Reuse accessory from cache with uuid 982243fc-936f-4965-b6c8-df3228a98a37 and name 0x60a423fffe2cd0e5
[3/3/2021, 10:23:04 PM] [ZigBee] Successfully auto discovered device: 0x60a423fffe2cd0e5, Temperature & humidity sensor
[3/3/2021, 10:23:04 PM] [ZigBee] Registered device: 0x60a423fffe2cd0e5 TUYATEC-yg5dcbfu RH3052
[3/3/2021, 10:23:04 PM] [ZigBee] Mounting device 0x60a423fffe2cd0e5...
[3/3/2021, 10:23:04 PM] [ZigBee] Initializing ZigBee device: 0xbc33acfffe3313b6 - TS0041 - _TZ3400_keyjqthh
[3/3/2021, 10:23:04 PM] [ZigBee] Reuse accessory from cache with uuid 09ac29ce-8b1d-4375-8e76-3feaaacfbb88 and name 0xbc33acfffe3313b6
[3/3/2021, 10:23:04 PM] [ZigBee] Successfully auto discovered device: 0xbc33acfffe3313b6, Wireless switch with 1 button
[3/3/2021, 10:23:04 PM] [ZigBee] Registered device: 0xbc33acfffe3313b6 _TZ3400_keyjqthh TS0041
[3/3/2021, 10:23:04 PM] [ZigBee] Mounting device 0xbc33acfffe3313b6...
[3/3/2021, 10:23:04 PM] [ZigBee] Initializing ZigBee device: 0x5c0272fffedb0f19 - TS0601 - _TZE200_2dpplnsn
[3/3/2021, 10:23:04 PM] [ZigBee] Reuse accessory from cache with uuid 3030368a-f9a0-4511-ac6d-d8250e763e8c and name 0x5c0272fffedb0f19
[3/3/2021, 10:23:04 PM] [ZigBee] Found class for device with key _TZE200_2dpplnsn:TS0601
[3/3/2021, 10:23:04 PM] [ZigBee] Entity '[object Object]' is unknown
[3/3/2021, 10:23:04 PM] [ZigBee] Initializing ZigBee device: 0x847127fffe93fcfe - TS0601 - _TZE200_ckud7u2l
[3/3/2021, 10:23:04 PM] [ZigBee] Reuse accessory from cache with uuid eb7068c3-a24a-41a7-b800-32a2e1c8fb04 and name 0x847127fffe93fcfe
[3/3/2021, 10:23:04 PM] [ZigBee] Found class for device with key _TZE200_ckud7u2l:TS0601
[3/3/2021, 10:23:04 PM] [ZigBee] Registered device: 0x847127fffe93fcfe _TZE200_ckud7u2l TS0601
[3/3/2021, 10:23:04 PM] [ZigBee] Mounting device 0x847127fffe93fcfe...
(node:3565) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: ZigBee Entity resolution failed
    at new ZigBeeAccessory (/usr/lib/node_modules/homebridge-zigbee-nt/src/accessories/zig-bee-accessory.ts:70:11)
    at new TuyaThermostatControl (/usr/lib/node_modules/homebridge-zigbee-nt/src/accessories/tuya/tuya-thermostat-control.ts:6:1)
    at Object.createAccessoryInstance (/usr/lib/node_modules/homebridge-zigbee-nt/src/registry.ts:87:14)
    at ZigbeeNTHomebridgePlatform.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/src/platform.ts:286:32)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/homebridge-zigbee-nt/dist/platform.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/homebridge-zigbee-nt/dist/platform.js:23:12)
    at ZigbeeNTHomebridgePlatform.initDevice (/usr/lib/node_modules/homebridge-zigbee-nt/dist/platform.js:218:16)
    at /usr/lib/node_modules/homebridge-zigbee-nt/src/platform.ts:224:68
(node:3565) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:3565) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by madchicken** [comment]
Ok, we need to remove your thermostat from supported devices, since is not recognised by the herdsman lib, as you can see from the two lines of logs:

```
[ZigBee] Found class for device with key _TZE200_2dpplnsn:TS0601
[ZigBee] Entity '[object Object]' is unknown
```

To support it, we need to wait that it is added to supported devices in `zigbee-herdsman-converters` project.
I'll push a new version without the thermostat support so you can start the plugin

**Comment by piokacz** [comment]
Hello @madchicken, this thermostat is paired with the dongle, but it's not present in the network - I just borrowed it for a while. Without the Web UI i cannot unpair the device - maybe this is the problem?

**Comment by madchicken** [comment]
Yes, it is the problem. Stay tuned, I'll push a new version soon, so you can use again the WEB UI

**Comment by madchicken** [comment]
Oh wait! They just added it https://github.com/Koenkk/zigbee2mqtt/issues/6088
Let me see if we can support it

**Comment by piokacz** [comment]
Hi, I saw You [Fix] Dismiss support for _TZE200_ckud7u2l TS0601 thermostat (#133), but my thermostat _TZE200_ckud7u2l TS0601 works fine and the other one _TZE200_2dpplnsn', ['TS0601'] is not present in my network write now

**Comment by madchicken** [comment]
Thanks for pointing that our, sorry for the confusion, I fixed the PR

**Comment by piokacz** [comment]
Hi @madchicken , in wersion 2.1.3 it's working:
```
[3/4/2021, 4:15:56 PM] [ZigBee] Starting WEB UI on port 9000, host is set to 0.0.0.0
[3/4/2021, 4:15:56 PM] [ZigBee] WebSocket server started @ null
[3/4/2021, 4:15:56 PM] [ZigBee] WEB UI Listening on port 9000
```
