### ISSUE TITLE
Disappearing temp & Humi (Tuya temperature and humidity sensor - RH3052)

### ISSUE THREAD

**Issue by piokacz** [madchicken/homebridge-zigbee-nt#141]
Hi, I have a problem with T&H sensor. After pushing the button the parameters are show in homebridge and home app, but after a while it is set to 0 without any information in logs - the time sometimes is few second but some times it last few minutes. Also the battery service doesn't work.

```
[3/22/2021, 5:23:14 PM] [ZigBee] Zigbee message from 0x60a423fffe2cd0e5 {
  type: 'attributeReport',
  device: Device {
    ID: 5,
    _type: 'EndDevice',
    _ieeeAddr: '0x60a423fffe2cd0e5',
    _networkAddress: 37636,
    _manufacturerID: 0,
    _endpoints: [ [Endpoint] ],
    _manufacturerName: 'TUYATEC-yg5dcbfu',
    _powerSource: 'Battery',
    _modelID: 'RH3052',
    _applicationVersion: 74,
    _stackVersion: 0,
    _zclVersion: 3,
    _hardwareVersion: 1,
    _dateCode: '20180608',
    _softwareBuildID: undefined,
    _interviewCompleted: true,
    _interviewing: false,
    _skipDefaultResponse: false,
    meta: {},
    _lastSeen: 1616430194916,
    temperature: 0,
    _linkquality: 76
  },
  endpoint: Endpoint {
    ID: 1,
    profileID: 260,
    deviceID: 770,
    inputClusters: [ 0, 1, 3, 1026, 1029 ],
    outputClusters: [ 3, 1026, 1029 ],
    deviceNetworkAddress: 37636,
    deviceIeeeAddress: '0x60a423fffe2cd0e5',
    clusters: {
      genBasic: [Object],
      msTemperatureMeasurement: [Object],
      msRelativeHumidity: [Object],
      genPowerCfg: [Object]
    },
    _binds: [],
    _configuredReportings: [],
    meta: {}
  },
  data: { measuredValue: 4699 },
  linkquality: 76,
  groupID: 0,
  cluster: 'msRelativeHumidity',
  meta: {
    zclTransactionSequenceNumber: 97,
    manufacturerCode: null,
    frameControl: {
      frameType: 0,
      manufacturerSpecific: false,
      direction: 1,
      disableDefaultResponse: true,
      reservedBits: 0
    }
  }
}
[3/22/2021, 5:23:14 PM] [ZigBee] Decoded state from incoming message { humidity: 46.99 }
[3/22/2021, 5:23:14 PM] [ZigBee] Updating state of device 0x60a423fffe2cd0e5 with  { humidity: 46.99 }
[3/22/2021, 5:23:14 PM] [ZigBee] Updated state for device 0x60a423fffe2cd0e5 is now  { temperature: 23.63, humidity: 46.99 }
[3/22/2021, 5:23:14 PM] [ZigBee] Updating service 00000082-0000-1000-8000-0026BB765291 for device 0x60a423fffe2cd0e5 with state { temperature: 23.63, humidity: 46.99 }
[3/22/2021, 5:23:14 PM] [ZigBee] Updating service 0000008A-0000-1000-8000-0026BB765291 for device 0x60a423fffe2cd0e5 with state { temperature: 23.63, humidity: 46.99 }
[3/22/2021, 5:23:14 PM] [ZigBee] Updating service 00000096-0000-1000-8000-0026BB765291 for device 0x60a423fffe2cd0e5 with state { temperature: 23.63, humidity: 46.99 }
```

![odczyt](https://user-images.githubusercontent.com/75645851/112025134-29751a80-8b35-11eb-9aef-91321fe2dca9.jpg)
<img width="1416" alt="Zrzut ekranu 2021-03-22 o 16 42 45" src="https://user-images.githubusercontent.com/75645851/112025168-33971900-8b35-11eb-95b0-c2bd33462a31.png">

**Comment by madchicken** [comment]
Does it happen with Home App too? Just to exclude a bug in the Homebridge UI.

**Comment by piokacz** [comment]
Hi @madchicken , yes it does. I put only information about homebridge just to exclude a bug in apple app :-)

**Comment by madchicken** [comment]
I will add some debug information in the next release, so we can understand where those zeroes are coming from...(it doesn't't make any sense at the moment, since I return the value I have in the state, that is correctly updated as you can see from your logs)

**Comment by madchicken** [comment]
Thanks @piokacz I was able to replicate this issue. Fix will come with next release

**Comment by piokacz** [comment]
Hi @madchicken version 2.2.2 didn't help it's still the issue, but I found this in logs in the time when temperature disappired:
`[3/26/2021, 12:14:04 AM] [ZigBee] No converter available for 'local_temperature'`
May be it will help - tomorrow I will read the logs once again

**Comment by piokacz** [comment]
More information about 'illegal value':
```
[3/26/2021, 12:14:04 AM] [ZigBee] Reading KEY 'current_heating_setpoint' from '0x847127fffe93fcfe'
[3/26/2021, 12:14:04 AM] [ZigBee] Reading 'current_heating_setpoint' for '0x847127fffe93fcfe' failed: 'TypeError: converter.convertGet is not a function'
[3/26/2021, 12:14:04 AM] [ZigBee] TypeError: converter.convertGet is not a function
    at ZigBeeClient.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/src/zigbee/zig-bee-client.ts:156:52)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/homebridge-zigbee-nt/dist/zigbee/zig-bee-client.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/homebridge-zigbee-nt/dist/zigbee/zig-bee-client.js:4:12)
    at ZigBeeClient.readDeviceState (/usr/lib/node_modules/homebridge-zigbee-nt/dist/zigbee/zig-bee-client.js:107:16)
    at ZigBeeClient.getCurrentHeatingSetpoint (/usr/lib/node_modules/homebridge-zigbee-nt/src/zigbee/zig-bee-client.ts:365:17)
    at ThermostatServiceBuilder.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/src/builders/thermostat-service-builder.ts:174:12)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/homebridge-zigbee-nt/dist/builders/thermostat-service-builder.js:8:71
[3/26/2021, 12:14:04 AM] [ZigBee] Device state (0x847127fffe93fcfe):  {}
[3/26/2021, 12:14:04 AM] [homebridge-zigbee-nt] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 5 exceeded minimum of 10. See https://git.io/JtMGR for more info.
[3/26/2021, 12:14:04 AM] [homebridge-zigbee-nt] Error: 
    at TargetTemperature.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at TargetTemperature.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1946:16)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1533:24
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at ThermostatServiceBuilder.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/src/builders/thermostat-service-builder.ts:182:9)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/homebridge-zigbee-nt/dist/builders/thermostat-service-builder.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/homebridge-zigbee-nt/dist/builders/thermostat-service-builder.js:4:12)
    at TargetTemperature.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/src/builders/thermostat-service-builder.ts:172:70)
[3/26/2021, 12:14:04 AM] [homebridge-zigbee-nt] This plugin generated a warning from the characteristic 'Current Heating Cooling State': characteristic was supplied illegal value: number 3 exceeded maximum of 2. See https://git.io/JtMGR for more info.
[3/26/2021, 12:14:04 AM] [homebridge-zigbee-nt] Error: 
    at CurrentHeatingCoolingState.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at CurrentHeatingCoolingState.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1950:16)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1533:24
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at ThermostatServiceBuilder.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/src/builders/thermostat-service-builder.ts:72:11)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/homebridge-zigbee-nt/dist/builders/thermostat-service-builder.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/homebridge-zigbee-nt/dist/builders/thermostat-service-builder.js:4:12)
    at CurrentHeatingCoolingState.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/src/builders/thermostat-service-builder.ts:70:87)
```

**Comment by piokacz** [comment]
@madchicken before auto discovery i took `xiaomi-temp-humi-sensor.ts` change the name to RH3052, register the device and the plugin work perfectly :-)

**Comment by madchicken** [comment]
xiaomi-temp-humi-sensor.ts uses the exact same code of the auto discovery device (all the accessories are now using builders). It would help to see if the auto discovery is actually finding something different (and wrong) about your device

**Comment by piokacz** [comment]
Hi, the answer after Homebridge restart - two of my sensors:

```
[3/28/2021, 9:42:40 PM] [ZigBee] Initializing ZigBee device: 0x60a423fffe029b7b - RH3052 - TUYATEC-yg5dcbfu
[3/28/2021, 9:42:40 PM] [ZigBee] Reuse accessory from cache with uuid 848737fa-56a0-41bd-bc63-b2bec685cd05 and name 0x60a423fffe029b7b
[3/28/2021, 9:42:40 PM] [ZigBee] Successfully auto discovered device: 0x60a423fffe029b7b, Temperature & humidity sensor [
  {
    "type": "humidity-sensor",
    "meta": {}
  },
  {
    "type": "temperature-sensor",
    "meta": {}
  },
  {
    "type": "battery",
    "meta": {}
  }
]
[3/28/2021, 9:42:40 PM] [ZigBee] Registered device: 0x60a423fffe029b7b TUYATEC-yg5dcbfu RH3052
[3/28/2021, 9:42:40 PM] [ZigBee] Mounting device 0x60a423fffe029b7b...
[3/28/2021, 9:42:40 PM] [ZigBee] Initializing ZigBee device: 0x60a423fffe2cd0e5 - RH3052 - TUYATEC-yg5dcbfu
[3/28/2021, 9:42:40 PM] [ZigBee] Reuse accessory from cache with uuid 982243fc-936f-4965-b6c8-df3228a98a37 and name 0x60a423fffe2cd0e5
[3/28/2021, 9:42:40 PM] [ZigBee] Successfully auto discovered device: 0x60a423fffe2cd0e5, Temperature & humidity sensor [
  {
    "type": "humidity-sensor",
    "meta": {}
  },
  {
    "type": "temperature-sensor",
    "meta": {}
  },
  {
    "type": "battery",
    "meta": {}
  }
]
[3/28/2021, 9:42:40 PM] [ZigBee] Registered device: 0x60a423fffe2cd0e5 TUYATEC-yg5dcbfu RH3052
[3/28/2021, 9:42:40 PM] [ZigBee] Mounting device 0x60a423fffe2cd0e5...
```

**Comment by madchicken** [comment]
Ok, it seems I left other stuff around. This happens because I start doing something on a day and I finish it five days lates...and I don't remember what I was doing 😓

**Comment by piokacz** [comment]
Thank you @madchicken - works perfekt

**Comment by piokacz** [comment]
@madchicken I lost humidity again after 4 hours :-) on one of my sensor, but after making the bath (change humi i room) it's on again.

**Comment by piokacz** [comment]
I lost the battery level also

**Comment by piokacz** [comment]
next 12 hours work without errors :-)
