### ISSUE TITLE
new install on newest homebridge error

### ISSUE THREAD

**Issue by Monthyz** [madchicken/homebridge-zigbee-nt#146]
Hello, on a very new homebridge install with successful install of homebridge-zigbee-nt thru UI of homebridge thru plugin section after first restart of homebridge I got this error message:

[25/03/2021, 21:18:43] ====================
[25/03/2021, 21:18:43] ERROR LOADING PLUGIN homebridge-zigbee-nt:
[25/03/2021, 21:18:43] /usr/local/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman-converters/node_modules/https-proxy-agent/dist/index.js:3
When extending the parser with plugins, you need to call these methods
     ^^^^^^^^^

SyntaxError: Unexpected identifier
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman-converters/lib/ota/common.js:3:25)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[25/03/2021, 21:18:43] ====================
[25/03/2021, 21:18:43] Loading 2 platforms...
[25/03/2021, 21:18:43] [Config] Initializing config platform...
[25/03/2021, 21:18:43] [Config] Running in Service Mode
[25/03/2021, 21:18:43] No plugin was found for the platform "ZigbeeHomebridgeNTPlatform" in your config.json. Please make sure the corresponding plugin is installed correctly.

Any recommendations? Thank you very much.

Tomas

**Comment by madchicken** [comment]
Could you provide some info about your environment? 

- Homebridge version
- Plugin version
- Node version

Thanks

**Comment by Monthyz** [comment]
here you go:

Homebridge v1.3.4
homebridge-zigbee-nt v2.2.1
Node.js Version v14.15.4

**Comment by Monthyz** [comment]
I tried homebridge-zigbee-nt v2.2.2 too. 

No luck

**Comment by Monthyz** [comment]
> Could you provide some info about your environment?
> 
> * Homebridge version
> * Plugin version
> * Node version
> 
> Thanks

Any ideas? Thank you

**Comment by madchicken** [comment]
No, sorry. It seems your installation is messed up. Somehow the js in the error above is containing some non javascript code.
You should try to reinstall the plugin from the CLI instead using the UI. Just open a terminal and type

    npm install homebridge-zigbee-nt -g --unsafe-perm
