### ISSUE TITLE
connect to hardware error

### ISSUE THREAD

**Issue by piokacz** [madchicken/homebridge-zigbee-nt#157]
My plugin was working stable for few weeks on v.2.2.4. Yesterday I installed the new motion sensor - aqara with lumi. I didn't have any problems with adding the sensor and it was working fine for about an hour. After an error I did few homebridge restarts, I even restart my rPi 3 times - but it didn't help. Bellow my HB logs.

```
[5/6/2021, 12:16:38 AM] [ZigBee] Retrying connect to hardware
(node:1961) UnhandledPromiseRejectionWarning: Error: SRSP - ZDO - startupFromApp after 40000ms
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/utils/waitress.ts:91:35)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:1961) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 104)
[5/6/2021, 12:18:10 AM] [ZigBee] Error: AREQ - ZDO - stateChangeInd after 60000ms
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/utils/waitress.ts:91:35)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[5/6/2021, 12:18:10 AM] [ZigBee] error: Error: Cannot request when znp has not been initialized yet
    at Znp.request (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:289:19)
    at ZStackAdapter.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:204:24)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:23:12)
    at ZStackAdapter.setLED (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:193:16)
    at Controller.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/controller/controller.ts:376:28)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/dist/controller/controller.js:24:58)
(node:1961) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getEntries' of null
    at Function.loadFromDatabaseIfNecessary (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/controller/model/device.ts:274:45)
    at Function.byType (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/controller/model/device.ts:293:16)
    at Controller.getDevicesByType (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/controller/controller.ts:319:23)
    at ZigBeeController.coordinator (/usr/lib/node_modules/homebridge-zigbee-nt/src/zigbee/zigBee-controller.ts:206:26)
    at ZigBeeClient.getCoordinator (/usr/lib/node_modules/homebridge-zigbee-nt/src/zigbee/zig-bee-client.ts:381:24)
    at ZigbeeNTHomebridgePlatform.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/src/platform.ts:213:44)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/homebridge-zigbee-nt/dist/platform.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/homebridge-zigbee-nt/dist/platform.js:23:12)
(node:1961) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 107)
```

**Comment by piokacz** [comment]
My Environment:

System | Raspbian GNU/Linux Buster (10)
node.js v12.20.1
npm v6.14.10

any suggestion @madchicken ?

**Comment by madchicken** [comment]
Uhm, this is a problem with the dongle. Have you tried to restart the raspberry? Please, attach your zig bee db, I might find something related to the coordinator config

**Comment by piokacz** [comment]
I restart the rPI few times, I've installed twice the plugin - when it starting connect to dongle the led is on, but after an error it's go off again. In /dev/ folder I can see the dongle, but I don't know how to check if it's working correct. I don't have the db because I removed the plugin and all of devices.

**Comment by madchicken** [comment]
I'd try to re-flash the dongle as last try.

**Comment by piokacz** [comment]
@madchicken thank you for your advice - it is hardware problem

**Comment by BananaJ0e** [comment]
i get the following error message:

[2021-6-23 13:32:07] [ZigBee] Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at Znp.<anonymous> (/usr/local/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:23:12)
    at SerialPort.<anonymous> (/usr/local/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:144:65)
    at SerialPort._error (/usr/local/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /usr/local/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12


i tried this, but the port isn'*t locked:
Error: Resource temporarily unavailable Cannot lock port #
This error occurs when another program is already using (and thus locking) the adapter. You can find out which via the following command: ls -l /proc/[0-9]/fd/ |grep /dev/ttyACM0 (replace /dev/ttyACM0 with your adapter port).
(https://www.zigbee2mqtt.io/information/FAQ.html#error-resource-temporarily-unavailable-cannot-lock-port)

what can i do?

**Comment by madchicken** [comment]
Did you try restarting the raspberry? I mean, by disconnecting the power...
