### ISSUE TITLE
Cannot read property 'configureKey' of undefined

### ISSUE THREAD

**Issue by noahbjohnson** [madchicken/homebridge-zigbee-nt#161]
It looks like this error is occurring with my MINIZB. It's the only router on the network and it functions correctly as far as I can tell, both routing and switching.

## Logs
This is repeated back-to-back. (see "rejection id: 991")
```
(node:908) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 991)
(node:908) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'configureKey' of undefined
    at ConfigurableAccessory.set isConfigured [as isConfigured] (/usr/lib/node_modules/homebridge-zigbee-nt/src/accessories/zig-bee-accessory.ts:207:74)
    at ConfigurableAccessory.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/src/accessories/zig-bee-accessory.ts:179:28)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/homebridge-zigbee-nt/dist/accessories/zig-bee-accessory.js:5:58)
    at runMicrotasks (<anonymous>)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at processTimers (internal/timers.js:494:9)
```

On restart with debug on:
```
[5/11/2021, 6:25:58 PM] [ZigBee] Reading KEY 'state' from '0xb4e3f9fffec64732'
[5/11/2021, 6:25:58 PM] [ZigBee] Zigbee message from 0xb4e3f9fffec64732 {
  type: 'readResponse',
  device: Device {
    ID: 2,
    _type: 'Router',
    _ieeeAddr: '0xb4e3f9fffec64732',
    _networkAddress: 35519,
    _manufacturerID: 4098,
    _endpoints: [ [Endpoint], [Endpoint] ],
    _manufacturerName: 'SONOFF',
    _powerSource: 'Mains (single phase)',
    _modelID: '01MINIZB',
    _applicationVersion: undefined,
    _stackVersion: undefined,
    _zclVersion: 3,
    _hardwareVersion: undefined,
    _dateCode: '20200927',
    _softwareBuildID: undefined,
    _interviewCompleted: true,
    _interviewing: false,
    _skipDefaultResponse: false,
    meta: {},
    _lastSeen: 1620757558526,
    _linkquality: 145
  },
  endpoint: Endpoint {
    ID: 1,
    profileID: 260,
    deviceID: 256,
    inputClusters: [ 0, 3, 4, 5, 6, 4096 ],
    outputClusters: [ 4096 ],
    deviceNetworkAddress: 35519,
    deviceIeeeAddress: '0xb4e3f9fffec64732',
    clusters: { genBasic: [Object], genOnOff: [Object] },
    _binds: [],
    _configuredReportings: [],
    meta: {}
  },
  data: { onOff: 0 },
  linkquality: 145,
  groupID: null,
  cluster: 'genOnOff',
  meta: {
    zclTransactionSequenceNumber: 16,
    manufacturerCode: null,
    frameControl: {
      frameType: 0,
      manufacturerSpecific: false,
      direction: 1,
      disableDefaultResponse: false,
      reservedBits: 0
    }
  }
}
[5/11/2021, 6:25:58 PM] [ZigBee] Decoded state from incoming message { state: 'OFF' }
[5/11/2021, 6:25:58 PM] [ZigBee] Updating state of device 0xb4e3f9fffec64732 with  { state: 'OFF' }
[5/11/2021, 6:25:58 PM] [ZigBee] Updated state for device 0xb4e3f9fffec64732 is now  { state: 'OFF' }
[5/11/2021, 6:25:58 PM] [ZigBee] Updating service 00000049-0000-1000-8000-0026BB765291 for device 0xb4e3f9fffec64732 with state { state: 'OFF' }
[5/11/2021, 6:25:58 PM] [ZigBee] Device state (0xb4e3f9fffec64732):  {}
(node:5153) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'configureKey' of undefined
    at ConfigurableAccessory.set isConfigured [as isConfigured] (/usr/lib/node_modules/homebridge-zigbee-nt/src/accessories/zig-bee-accessory.ts:207:74)
    at ConfigurableAccessory.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/src/accessories/zig-bee-accessory.ts:179:28)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/homebridge-zigbee-nt/dist/accessories/zig-bee-accessory.js:5:58)
(node:5153) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)

[5/11/2021, 6:26:58 PM] [ZigBee] Reading KEY 'state' from '0xb4e3f9fffec64732'
[5/11/2021, 6:26:58 PM] [ZigBee] Zigbee message from 0xb4e3f9fffec64732 {
  type: 'readResponse',
  device: Device {
    ID: 2,
    _type: 'Router',
    _ieeeAddr: '0xb4e3f9fffec64732',
    _networkAddress: 35519,
    _manufacturerID: 4098,
    _endpoints: [ [Endpoint], [Endpoint] ],
    _manufacturerName: 'SONOFF',
    _powerSource: 'Mains (single phase)',
    _modelID: '01MINIZB',
    _applicationVersion: undefined,
    _stackVersion: undefined,
    _zclVersion: 3,
    _hardwareVersion: undefined,
    _dateCode: '20200927',
    _softwareBuildID: undefined,
    _interviewCompleted: true,
    _interviewing: false,
    _skipDefaultResponse: false,
    meta: {},
    _lastSeen: 1620757618526,
    _linkquality: 145
  },
  endpoint: Endpoint {
    ID: 1,
    profileID: 260,
    deviceID: 256,
    inputClusters: [ 0, 3, 4, 5, 6, 4096 ],
    outputClusters: [ 4096 ],
    deviceNetworkAddress: 35519,
    deviceIeeeAddress: '0xb4e3f9fffec64732',
    clusters: { genBasic: [Object], genOnOff: [Object] },
    _binds: [],
    _configuredReportings: [],
    meta: {}
  },
  data: { onOff: 0 },
  linkquality: 145,
  groupID: null,
  cluster: 'genOnOff',
  meta: {
    zclTransactionSequenceNumber: 17,
    manufacturerCode: null,
    frameControl: {
      frameType: 0,
      manufacturerSpecific: false,
      direction: 1,
      disableDefaultResponse: false,
      reservedBits: 0
    }
  }
}
[5/11/2021, 6:26:58 PM] [ZigBee] Decoded state from incoming message { state: 'OFF' }
[5/11/2021, 6:26:58 PM] [ZigBee] Updating state of device 0xb4e3f9fffec64732 with  { state: 'OFF' }
[5/11/2021, 6:26:58 PM] [ZigBee] Updated state for device 0xb4e3f9fffec64732 is now  { state: 'OFF' }
[5/11/2021, 6:26:58 PM] [ZigBee] Updating service 00000049-0000-1000-8000-0026BB765291 for device 0xb4e3f9fffec64732 with state { state: 'OFF' }
[5/11/2021, 6:26:58 PM] [ZigBee] Device state (0xb4e3f9fffec64732):  {}
(node:5153) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'configureKey' of undefined
    at ConfigurableAccessory.set isConfigured [as isConfigured] (/usr/lib/node_modules/homebridge-zigbee-nt/src/accessories/zig-bee-accessory.ts:207:74)
    at ConfigurableAccessory.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/src/accessories/zig-bee-accessory.ts:179:28)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/homebridge-zigbee-nt/dist/accessories/zig-bee-accessory.js:5:58)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at processTimers (internal/timers.js:494:9)
(node:5153) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
```

## Config

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "0E:E1:23:A2:21:xx",
        "port": 51433,
        "pin": "567-52-xxx"
    },
    "accessories": [
        {
            "name": "Air Purifier",
            "deviceId": "foobar",
            "nameAirQuality": "AQ",
            "showAirQuality": true,
            "showPlasmawave": true,
            "accessory": "WinixC545"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "email": "foobar",
            "password": "foobar",
            "platform": "myQ"
        },
        {
            "name": "ZigBee",
            "port": "/dev/ttyACM0",
            "channel": 17,
            "secondaryChannel": "19",
            "adapter": "deconz",
            "routerPollingInterval": 30,
            "disableRouterPolling": false,
            "disableHttpServer": false,
            "disableLed": false,
            "preferAutoDiscover": false,
            "customDeviceSettings": [
                {
                    "ieeeAddr": "foobar",
                    "friendlyName": "Front Door"
                },
                {
                    "ieeeAddr": "foobar",
                    "friendlyName": "Front Room Window"
                }
            ],
            "platform": "ZigbeeHomebridgeNTPlatform"
        }
    ]
}
```

## Environment
```
noah@fleetwood:~$ uname -a
Linux fleetwood 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
```
noah@fleetwood:~$ sudo lsusb -t
/:  Bus 04.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 5000M
/:  Bus 03.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 480M
    |__ Port 1: Dev 5, If 0, Class=Communications, Driver=cdc_acm, 12M
    |__ Port 1: Dev 5, If 1, Class=CDC Data, Driver=cdc_acm, 12M
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=ehci-pci/2p, 480M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/8p, 480M
        |__ Port 8: Dev 3, If 0, Class=Hub, Driver=hub/2p, 480M
            |__ Port 1: Dev 4, If 0, Class=Hub, Driver=hub/3p, 12M
                |__ Port 3: Dev 8, If 1, Class=Wireless, Driver=btusb, 12M
                |__ Port 3: Dev 8, If 2, Class=Vendor Specific Class, Driver=btusb, 12M
                |__ Port 3: Dev 8, If 0, Class=Vendor Specific Class, Driver=btusb, 12M
                |__ Port 3: Dev 8, If 3, Class=Application Specific Interface, Driver=, 12M
            |__ Port 2: Dev 5, If 0, Class=Human Interface Device, Driver=usbhid, 1.5M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=ehci-pci/2p, 480M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/6p, 480M
```

Node.js Version | v14.16.1

**Comment by noahbjohnson** [comment]
Without really digging into the functionality, it seems like it should be a minor code fix. 

https://github.com/madchicken/homebridge-zigbee-nt/blob/0a1b568d2a7c4120cdce7ecef207536b356ce2b2/src/accessories/zig-bee-accessory.ts#L205-L211

This should at least prevent the log spam and anything needed could be sent to debug.

```ts
private set isConfigured(val: boolean) { 
   if (val === true) { 
     if (this.zigBeeDefinition.meta){
       this.zigBeeDefinition.meta.configured = this.zigBeeDefinition.meta.configureKey; 
     } else {
        // debug error?
        return
   } else { 
     delete this.zigBeeDefinition.meta?.configured; 
   } 
 } 
```

**Comment by noahbjohnson** [comment]
Following the stack, it looks like L179 is the one calling the setter. Maybe the `this.zigBeeDefinition.configure` call isn't completing before resolving?
https://github.com/madchicken/homebridge-zigbee-nt/blob/0a1b568d2a7c4120cdce7ecef207536b356ce2b2/src/accessories/zig-bee-accessory.ts#L172-L199

**Comment by rforro** [comment]
The same happens with **IKEA of Sweden TRADFRI bulb E27 WW 806lm** Model **LED1836G9**.

**Comment by manuchis** [comment]
Any solution yet? I had to re-install everything I cannot pair my devices anymore  because of this :(
