### ISSUE TITLE
No response from 0x5c0272fffe898f91. Is it online?

### ISSUE THREAD

**Issue by andrewbpowers** [madchicken/homebridge-zigbee-nt#166]
I install Homebridge Zigbee Nt three times... doesn't work!
See the log:

`[23/05/2021, 18:49:49] [ZigbeeHomebridgeNTPlatform] Accepting joining whitelisted device '0x5c0272fffe898f91'
[23/05/2021, 18:49:49] [ZigbeeHomebridgeNTPlatform] Device joined, Adding 0x5c0272fffa342f91 (undefined - undefined)
[23/05/2021, 18:49:49] [ZigbeeHomebridgeNTPlatform] Interview progress started for device 0x5c0272fffa342f91
[23/05/2021, 18:49:50] [ZigbeeHomebridgeNTPlatform] Initializing ZigBee device: 0x5c0272fffa342f91 - undefined - undefined
[23/05/2021, 18:49:50] [ZigbeeHomebridgeNTPlatform] Unsupported ZigBee device: 0x5c0272fffa342f91 - undefined - undefined
[23/05/2021, 18:49:52] [ZigbeeHomebridgeNTPlatform] Accepting joining whitelisted device '0x5c0272fffa342f91'
[23/05/2021, 18:49:53] [ZigbeeHomebridgeNTPlatform] Device announce: 0x5c0272fffa342f91 (undefined - undefined)
[23/05/2021, 18:49:53] [ZigbeeHomebridgeNTPlatform] Not initializing device 0x5c0272fffa342f91: interview process still not completed
[23/05/2021, 18:51:00] [ZigbeeHomebridgeNTPlatform] Successfully interviewed device: IKEA of Sweden - TRADFRI bulb E27 WS opal 1000lm
[23/05/2021, 18:51:02] [ZigbeeHomebridgeNTPlatform] Initializing ZigBee device: 0x5c0272fffa342f91 - TRADFRI bulb E27 WS opal 1000lm - IKEA of Sweden
[23/05/2021, 18:51:02] [ZigbeeHomebridgeNTPlatform] Registering new accessory with uuid 580dfe56-g394-4183-b0b1-7cc816e6dcb0 and name 0x5c0272fffa342f91
[23/05/2021, 18:51:02] [ZigbeeHomebridgeNTPlatform] Registered device: 0x5c0272fffa342f91 IKEA of Sweden TRADFRI bulb E27 WS opal 1000lm
[23/05/2021, 18:51:02] [ZigbeeHomebridgeNTPlatform] Mounting device 0x5c0272fffa342f91...
[23/05/2021, 18:51:03] [ZigbeeHomebridgeNTPlatform] Device 0x5c0272fffa342f91 is a router, install ping
[23/05/2021, 18:51:05] [ZigbeeHomebridgeNTPlatform] this.zigBeeDeviceDescriptor.updateLastSeen is not a function TypeError: this.zigBeeDeviceDescriptor.updateLastSeen is not a function
    at ConfigurableAccessory.internalUpdate (/usr/local/lib/node_modules/homebridge-zigbee-nt/src/accessories/zig-bee-accessory.ts:227:35)
    at /usr/local/lib/node_modules/homebridge-zigbee-nt/src/platform.ts:416:25
    at ZigBeeClient.decodeMessage (/usr/local/lib/node_modules/homebridge-zigbee-nt/src/zigbee/zig-bee-client.ts:138:5)
    at ZigbeeNTHomebridgePlatform.handleZigBeeMessage (/usr/local/lib/node_modules/homebridge-zigbee-nt/src/platform.ts:414:19)
    at Controller.<anonymous> (/usr/local/lib/node_modules/homebridge-zigbee-nt/src/platform.ts:124:71)
    at Controller.emit (events.js:315:20)
    at Controller.<anonymous> (/usr/local/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/controller/controller.ts:666:18)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/dist/controller/controller.js:27:71
    at new Promise (<anonymous>)`

Thanks in advance for any tip and help! :-)

Take care...

**Comment by andrewbpowers** [comment]
Can be closed with pleasure. I switched to another system, which worked immediately and runs without problems.
Take care...

**Comment by LouwHopley** [comment]
Hi @andrewbpowers , to what system did you switch? Was it perhaps a different homebridge plugin, or different hardware entirely? I'm having the same issues as above.

**Comment by andrewbpowers** [comment]
Hello @LouwHopley !
Thank for your feedback. :-)

I really gave HB and Zigbee-NT the  a chance, but in the end it just didn't work without problems and pain. I'm also not sure if it ended up being HB or the plugin or the combination. I then just tried Home Assistant and everything worked immediately in terms of IKEA ZigBee light bulb. The bulb was recognized in seconds and works without any problems, even as far as dimming and color settings are concerned.

Have a nice day and take care...

**Comment by manuchis** [comment]
Well, despite AdrewbPowers left, I also have this problem with the lightbulbs and is unusable... :( it seems that many errors came with the update of herdsman plugin or something.
