### ISSUE TITLE
zigbee-nt cannot find module

### ISSUE THREAD

**Issue by reovadea** [madchicken/homebridge-zigbee-nt#181]
This issue was reported before with a workaround and fixed and closed. But with the most recent versions of both homebridge and this plugin, the error seems to bee back.

```[8/2/2021, 6:53:57 PM] ====================
[8/2/2021, 6:53:57 PM] ERROR LOADING PLUGIN homebridge-zigbee-nt:
[8/2/2021, 6:53:57 PM] Error: Cannot find module 'homebridge/lib/logger'
Require stack:
- /homebridge/node_modules/homebridge-zigbee-nt/dist/web/api/http-server.js
- /homebridge/node_modules/homebridge-zigbee-nt/dist/platform.js
- /homebridge/node_modules/homebridge-zigbee-nt/dist/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-zigbee-nt/src/web/api/http-server.ts:14:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
[8/2/2021, 6:53:57 PM] ====================```

**Comment by madchicken** [comment]
Should be fixed in #2.5.1
