### ISSUE TITLE
Build Issue on Raspian Buster with 2.5.1 

### ISSUE THREAD

**Issue by maccoylton** [madchicken/homebridge-zigbee-nt#184]
I have been able to build the previous versions without issue. Today I pulled 2.5.1 and am getting the following build issues:- 

yarn && yarn build 
yarn install v1.22.5
[1/5] Validating package.json...
warning homebridge-zigbee-nt@2.5.1: The engine "homebridge" appears to be invalid.
[2/5] Resolving packages...
warning Resolution field "@types/react@17.0.0" is incompatible with requested version "@types/react@^16.9.5"
warning Resolution field "node-fetch@2.6.1" is incompatible with requested version "node-fetch@^1.0.1"
success Already up-to-date.
Done in 2.65s.
yarn run v1.22.5
warning homebridge-zigbee-nt@2.5.1: The engine "homebridge" appears to be invalid.
$ yarn clean && yarn build:ts && yarn build:ui
warning homebridge-zigbee-nt@2.5.1: The engine "homebridge" appears to be invalid.
$ rimraf dist/
warning homebridge-zigbee-nt@2.5.1: The engine "homebridge" appears to be invalid.
$ tsc
warning homebridge-zigbee-nt@2.5.1: The engine "homebridge" appears to be invalid.
$ parcel build public/index.html --dist-dir dist/public
Error: Cannot find module './artifacts/index.linux-arm-gnueabihf.node'
Require stack:
- /home/pi/homebridge-zigbee-nt/node_modules/@parcel/source-map/parcel_sourcemap_node/index.js
- /home/pi/homebridge-zigbee-nt/node_modules/@parcel/source-map/dist/node.js
- /home/pi/homebridge-zigbee-nt/node_modules/@parcel/core/lib/Parcel.js
- /home/pi/homebridge-zigbee-nt/node_modules/@parcel/core/lib/index.js
- /home/pi/homebridge-zigbee-nt/node_modules/parcel/lib/cli.js
- /home/pi/homebridge-zigbee-nt/node_modules/parcel/lib/bin.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/home/pi/homebridge-zigbee-nt/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/pi/homebridge-zigbee-nt/node_modules/@parcel/source-map/parcel_sourcemap_node/index.js:15:18)
    at Module._compile (/home/pi/homebridge-zigbee-nt/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/homebridge-zigbee-nt/node_modules/@parcel/source-map/parcel_sourcemap_node/index.js',
    '/home/pi/homebridge-zigbee-nt/node_modules/@parcel/source-map/dist/node.js',
    '/home/pi/homebridge-zigbee-nt/node_modules/@parcel/core/lib/Parcel.js',
    '/home/pi/homebridge-zigbee-nt/node_modules/@parcel/core/lib/index.js',
    '/home/pi/homebridge-zigbee-nt/node_modules/parcel/lib/cli.js',
    '/home/pi/homebridge-zigbee-nt/node_modules/parcel/lib/bin.js'
  ]
}
error Command failed with exit code 1.

**Comment by madchicken** [comment]
Can you tell me which version of node are you using? I suspect some incompatibility with parcel

**Comment by maccoylton** [comment]
v14.17.4

**Comment by madchicken** [comment]
This is weird: I was able to replicate the problem, but I don't know how to solve it. I am digging inside the parcel documentation/issues to understand why that file is missing

**Comment by maccoylton** [comment]
ok .. let me know if there is anything I can test at my end

**Comment by maccoylton** [comment]
Loks like this is a know issue in parcel, for which there a fix, but still doesn't work for me in Raspian

**Comment by madchicken** [comment]
@maccoylton can you point me to the "fix" so I can test it on my side?

**Comment by maccoylton** [comment]
https://github.com/parcel-bundler/parcel/issues/6947

**Comment by maccoylton** [comment]
FYI I logged a second bug report with parcel, even with the night build I still had an issue:- 

https://github.com/parcel-bundler/parcel/issues/6967
