### ISSUE TITLE
2.5.3 appear to breaks ZigBee on Raspian, looks like zigbee herdsman updated serialport package and then reversed that update due to issues

### ISSUE THREAD

**Issue by maccoylton** [madchicken/homebridge-zigbee-nt#190]
Just pulled the latest  sources and ZigBee bears to be partially broken:- 
 
[13/09/2021, 18:49:40] Homebridge v1.3.4 (Homebridge 1062) is running on port 51870.
[13/09/2021, 18:49:40] [ZigBee] Configured port for ZigBee dongle is /dev/ttyACM0
[13/09/2021, 18:49:40] [ZigBee] Initializing ZigBee controller on port /dev/ttyACM0 and channels 11, 25 (pan ID 6754)
[13/09/2021, 18:50:45] [ZigBee] Error: AREQ - ZDO - stateChangeInd after 60000ms
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
[13/09/2021, 18:50:45] [ZigBee] Zigbee: disabling joining new devices.
[13/09/2021, 18:50:45] [ZigBee] Retrying connect to hardware
[13/09/2021, 18:50:51] [ZigBee] Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
[13/09/2021, 18:50:51] [ZigBee] Zigbee: disabling joining new devices.
[13/09/2021, 18:50:51] [ZigBee] Retrying connect to hardware
[13/09/2021, 18:50:56] [ZigBee] Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
[13/09/2021, 18:50:56] [ZigBee] Zigbee: disabling joining new devices.
[13/09/2021, 18:50:56] [ZigBee] Retrying connect to hardware
[13/09/2021, 18:51:01] [ZigBee] Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
[13/09/2021, 18:51:01] [ZigBee] Zigbee: disabling joining new devices.
[13/09/2021, 18:51:01] [ZigBee] Retrying connect to hardware
[13/09/2021, 18:51:07] [ZigBee] Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
[13/09/2021, 18:51:07] [ZigBee] Zigbee: disabling joining new devices.
[13/09/2021, 18:51:07] [ZigBee] Retrying connect to hardware
[13/09/2021, 18:51:12] [ZigBee] Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
[13/09/2021, 18:51:12] [ZigBee] Zigbee: disabling joining new devices.
[13/09/2021, 18:51:12] [ZigBee] Retrying connect to hardware
[13/09/2021, 18:51:17] [ZigBee] Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
[13/09/2021, 18:51:17] [ZigBee] Zigbee: disabling joining new devices.
[13/09/2021, 18:51:17] [ZigBee] Retrying connect to hardware
[13/09/2021, 18:51:22] [ZigBee] Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
[13/09/2021, 18:51:22] [ZigBee] Zigbee: disabling joining new devices.
[13/09/2021, 18:51:22] [ZigBee] Retrying connect to hardware
[13/09/2021, 18:51:28] [ZigBee] Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
[13/09/2021, 18:51:28] [ZigBee] Zigbee: disabling joining new devices.
[13/09/2021, 18:51:28] [ZigBee] Retrying connect to hardware
[13/09/2021, 18:51:33] [ZigBee] Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
[13/09/2021, 18:51:33] [ZigBee] Zigbee: disabling joining new devices.
[13/09/2021, 18:51:33] [ZigBee] Retrying connect to hardware
[13/09/2021, 18:51:38] [ZigBee] Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
[13/09/2021, 18:51:38] [ZigBee] Zigbee: disabling joining new devices.
[13/09/2021, 18:51:38] [ZigBee] Retrying connect to hardware
[13/09/2021, 18:51:43] [ZigBee] Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
[13/09/2021, 18:51:43] [ZigBee] Zigbee: disabling joining new devices.
[13/09/2021, 18:51:43] [ZigBee] Retrying connect to hardware
[13/09/2021, 18:51:49] [ZigBee] Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
[13/09/2021, 18:51:49] [ZigBee] Zigbee: disabling joining new devices.
[13/09/2021, 18:51:49] [ZigBee] Retrying connect to hardware
[13/09/2021, 18:51:54] [ZigBee] Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
[13/09/2021, 18:51:54] [ZigBee] Zigbee: disabling joining new devices.
[13/09/2021, 18:51:54] [ZigBee] Retrying connect to hardware
[13/09/2021, 18:51:59] [ZigBee] Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
[13/09/2021, 18:51:59] [ZigBee] Zigbee: disabling joining new devices.
[13/09/2021, 18:51:59] [ZigBee] Retrying connect to hardware
[13/09/2021, 18:52:04] [ZigBee] Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
[13/09/2021, 18:52:04] [ZigBee] Zigbee: disabling joining new devices.
[13/09/2021, 18:52:04] [ZigBee] Retrying connect to hardware
[13/09/2021, 18:52:10] [ZigBee] Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
[13/09/2021, 18:52:10] [ZigBee] Zigbee: disabling joining new devices.
[13/09/2021, 18:52:10] [ZigBee] Retrying connect to hardware
[13/09/2021, 18:52:15] [ZigBee] Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
[13/09/2021, 18:52:15] [ZigBee] Zigbee: disabling joining new devices.
[13/09/2021, 18:52:15] [ZigBee] Retrying connect to hardware
[13/09/2021, 18:52:20] [ZigBee] Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
[13/09/2021, 18:52:20] [ZigBee] Zigbee: disabling joining new devices.
[13/09/2021, 18:52:20] [ZigBee] Retrying connect to hardware
[13/09/2021, 18:52:25] [ZigBee] Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
[13/09/2021, 18:52:25] [ZigBee] Zigbee: disabling joining new devices.
[13/09/2021, 18:52:25] [ZigBee] Retrying connect to hardware
[13/09/2021, 18:52:31] [ZigBee] Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
[13/09/2021, 18:52:31] [ZigBee] Zigbee: disabling joining new devices.
[13/09/2021, 18:52:31] [ZigBee] error: TypeError: Cannot read property 'permitJoin' of undefined
    at Controller.permitJoinInternal (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/controller/controller.ts:252:35)
    at Controller.permitJoin (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/controller/controller.ts:207:9)
[13/09/2021, 18:52:31] [ZigBee] ZigBee platform initialized @ 0x00124b001cdc5f5d
[13/09/2021, 18:52:31] [ZigBee] Reuse accessory from cache with uuid 6895c160-ba25-497f-b805-38071c751c56 and name zigbee:permit-join
[13/09/2021, 18:52:31] [ZigBee] Zigbee: disabling joining new devices.
[13/09/2021, 18:52:31] [ZigBee] PermitJoin accessory successfully registered
[13/09/2021, 18:52:31] [ZigBee] Reuse accessory from cache with uuid 4994893c-ea77-4292-a4ad-09e1f36f7099 and name zigbee:touchlink
[13/09/2021, 18:52:31] [ZigBee] TouchLink accessory successfully registered
[13/09/2021, 18:52:31] [ZigBee] Initializing ZigBee device: Conservatory Radiator - TS0601 - _TZE200_ckud7u2l
[13/09/2021, 18:52:31] [ZigBee] Reuse accessory from cache with uuid e4824cbc-2b0d-42e4-9fd5-c286bc45203f and name 0x5c0272fffec8901f
[13/09/2021, 18:52:31] [ZigBee] Found class for device with key _TZE200_ckud7u2l:TS0601
[13/09/2021, 18:52:31] [ZigBee] Registered device: Conservatory Radiator _TZE200_ckud7u2l TS0601
[13/09/2021, 18:52:31] [ZigBee] Mounting device Conservatory Radiator...
[13/09/2021, 18:52:31] [ZigBee] Initializing ZigBee device: Office Radiator - TS0601 - _TZE200_ckud7u2l
[13/09/2021, 18:52:31] [ZigBee] Reuse accessory from cache with uuid 2425c332-e4af-4386-a704-c35cbe5eb920 and name 0x847127fffe1dbcc5
[13/09/2021, 18:52:31] [ZigBee] Found class for device with key _TZE200_ckud7u2l:TS0601
[13/09/2021, 18:52:31] [ZigBee] Registered device: Office Radiator _TZE200_ckud7u2l TS0601
[13/09/2021, 18:52:31] [ZigBee] Mounting device Office Radiator...
[13/09/2021, 18:52:31] [ZigBee] Initializing ZigBee device: 0x00124b002265c361 - DS01 - eWeLink
[13/09/2021, 18:52:31] [ZigBee] Reuse accessory from cache with uuid 44294822-4e26-4567-afa2-bc13415c633b and name 0x00124b002265c361
[13/09/2021, 18:52:31] [ZigBee] Found class for device with key eWeLink:DS01
[13/09/2021, 18:52:31] [ZigBee] Registered device: 0x00124b002265c361 eWeLink DS01
[13/09/2021, 18:52:31] [ZigBee] Mounting device 0x00124b002265c361...
[13/09/2021, 18:52:31] [ZigBee] Initializing ZigBee device: 0x00124b0019387898 - lumi.router - LUMI

**Comment by maccoylton** [comment]
https://github.com/Koenkk/zigbee-herdsman/commit/18fbd5dd4689969a9a3e2e6bce2ab808af5d630f

**Comment by maccoylton** [comment]
After downgrading to 2.5.2 still did't work until I re-flashed  my Zigbee adapter.

**Comment by madchicken** [comment]
Thanks for reporting this @maccoylton, I just released a new version and forced the downgrade of the serialport package
