### ISSUE TITLE
Could not locate the bindings file / Cannot find module 'homebridge/lib/logger'

### ISSUE THREAD

**Issue by svenadlung** [madchicken/homebridge-zigbee-nt#194]
Hello,

thank you for providing this plugin. I appreciate it very much. Unfortunately, after installing and restarting, I get the following errors in the logs:

```
[9/17/2021, 9:16:36 AM] ERROR LOADING PLUGIN homebridge-zigbee-nt:
[9/17/2021, 9:16:36 AM] Error: Could not locate the bindings file. Tried:
 → /homebridge/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/build/bindings.node
 → /homebridge/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/build/Debug/bindings.node
 → /homebridge/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/build/Release/bindings.node
 → /homebridge/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/out/Debug/bindings.node
 → /homebridge/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/Debug/bindings.node
 → /homebridge/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/out/Release/bindings.node
 → /homebridge/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/Release/bindings.node
 → /homebridge/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/build/default/bindings.node
 → /homebridge/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/compiled/14.17.6/linux/x64/bindings.node
 → /homebridge/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/addon-build/release/install-root/bindings.node
 → /homebridge/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/addon-build/debug/install-root/bindings.node
 → /homebridge/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/addon-build/default/install-root/bindings.node
 → /homebridge/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/lib/binding/node-v83-linux-x64/bindings.node
    at bindings (/homebridge/node_modules/homebridge-zigbee-nt/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/lib/linux.js:2:36)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/lib/index.js:14:22)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
```

Any idea?

Best regards.

**Comment by svenadlung** [comment]
Okay, since I am running Homebridge in Docker (on Synology NAS) with Alpine Linux, I needed to manually reinstall SerialPort like described here: https://serialport.io/docs/guide-installation/#alpine-linux

```
# Change directory
cd /homebridge/node_modules/homebridge-zigbee-nt/node_modules/

# Install SerialPort
npm install serialport --unsafe-perm --build-from-source=serialport
```

Now there is a new error coming up:

`Error: Cannot find module 'homebridge/lib/logger'`

I've seen this a few times in closed issues. Lastly here: https://github.com/madchicken/homebridge-zigbee-nt/issues/181

@madchicken Do you have any idea? I am using newest version (2.5.3)

**Comment by svenadlung** [comment]
Okay, installing homebridge as a peer dependency seems to make it 

`npm install homebridge`

Still struggling with some permission errors, since SerialPort is not able to access /dev but this might be related to Docker. Will close the ticket.

**Comment by madchicken** [comment]
weird, but it's probably something due to some assumption on libraries paths that are not in line with running home bridge in docker...let me know if you find something more, we could add a page on the wiki regarding this problem
