### ISSUE TITLE
IKEA Tradfri repeater support

### ISSUE THREAD

**Issue by piokacz** [madchicken/homebridge-zigbee-nt#203]
Hi, I'm ussing the latest version of plugin. Today I install Ikea repeater. The log below:
```
(node:21039) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'configured' of undefined
    at IkeaSignalRepeater.set isConfigured [as isConfigured] (/usr/lib/node_modules/homebridge-zigbee-nt/src/accessories/zig-bee-accessory.ts:209:46)
    at IkeaSignalRepeater.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/src/accessories/zig-bee-accessory.ts:178:28)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/homebridge-zigbee-nt/dist/accessories/zig-bee-accessory.js:5:58)
(node:21039) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 55)
```

**Comment by madchicken** [comment]
Should be fixed in version 2.5.5
