### ISSUE TITLE
Can not Find CC2531 Error while connecting

### ISSUE THREAD

**Issue by pillemats** [madchicken/homebridge-zigbee-nt#207]
hi 

My HW is

- HB on Debian10 VM 
- CC2531 USB Stick flashed

i want to connect it to HB with this settings

` {
            "name": "ZigBee",
            "channel": 11,
            "secondaryChannel": "25",
            "adapter": "zstack",
            "routerPollingInterval": 30,
            "disableRouterPolling": false,
            "disableHttpServer": false,
            "disableLed": false,
            "preferAutoDiscover": false,
            "platform": "ZigbeeHomebridgeNTPlatform"
        },`

if i start HB at first it comes this:

`[20.10.2021, 21:36:14] [ZigBee] Configured port for ZigBee dongle is /dev/ttyACM0
[20.10.2021, 21:36:14] [ZigBee] Initializing ZigBee controller on port /dev/ttyACM0 and channels 11, 25 (pan ID 6754)`

and than this:

`[20.10.2021, 21:32:29] [ZigBee] Zigbee: disabling joining new devices.
[20.10.2021, 21:32:29] [ZigBee] Retrying connect to hardware
[20.10.2021, 21:32:34] [ZigBee] Error: Error while opening serialport 'Error: Error: Permission denied, cannot open /dev/ttyACM0'
    at SerialPort.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
[20.10.2021, 21:32:34] [ZigBee] Zigbee: disabling joining new devices.
[20.10.2021, 21:32:34] [ZigBee] Retrying connect to hardware
[20.10.2021, 21:32:39] [ZigBee] Error: Error while opening serialport 'Error: Error: Permission denied, cannot open /dev/ttyACM0'
    at SerialPort.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
[20.10.2021, 21:32:39] [ZigBee] Zigbee: disabling joining new devices.
[20.10.2021, 21:32:39] [ZigBee] error: TypeError: Cannot read property 'permitJoin' of undefined
    at Controller.permitJoinInternal (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/controller/controller.ts:252:35)
    at Controller.permitJoin (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/controller/controller.ts:207:9)
(node:842) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'ieeeAddr' of undefined
    at ZigbeeNTHomebridgePlatform.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/src/platform.ts:214:57)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/homebridge-zigbee-nt/dist/platform.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/homebridge-zigbee-nt/dist/platform.js:23:12)
    at ZigbeeNTHomebridgePlatform.handleZigBeeReady (/usr/lib/node_modules/homebridge-zigbee-nt/dist/platform.js:170:16)
    at ZigbeeNTHomebridgePlatform.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/src/platform.ts:126:16)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/homebridge-zigbee-nt/dist/platform.js:24:58)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:842) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:842) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

What is here the problem?

**Comment by madchicken** [comment]
This is a permission issue due to the system not allowing you to use the port. I am not an expert on this, so my help is limited here. As a _temporary_ workaorund, you could try to give permissions from the CLI, like this:

    sudo chmod 666 /dev/ttyACM0

but I would suggest to search on google a cleaner and definitive way to do it
