### ISSUE TITLE
Issue building latest version on Raspberry PI OS - Bullseye. Serial port bindings

### ISSUE THREAD

**Issue by maccoylton** [madchicken/homebridge-zigbee-nt#209]
Any ideas how to fix?

`[01/11/2021, 14:13:50] ====================
[01/11/2021, 14:13:50] ERROR LOADING PLUGIN homebridge-zigbee-nt:
[01/11/2021, 14:13:50] Error: Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/build/bindings.node
 → /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/build/Debug/bindings.node
 → /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/build/Release/bindings.node
 → /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/out/Debug/bindings.node
 → /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/Debug/bindings.node
 → /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/out/Release/bindings.node
 → /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/Release/bindings.node
 → /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/build/default/bindings.node
 → /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/compiled/14.18.1/linux/arm/bindings.node
 → /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/addon-build/release/install-root/bindings.node
 → /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/addon-build/debug/install-root/bindings.node
 → /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/addon-build/default/install-root/bindings.node
 → /usr/lib/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/lib/binding/node-v83-linux-arm/bindings.node
    at bindings (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/lib/linux.js:2:36)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/lib/index.js:14:22)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
[01/11/2021, 14:13:50] ====================`

**Comment by maccoylton** [comment]
npm was broken, seems by my upgrade to bullseye. It was trying to install packages into the wrong place
