### ISSUE TITLE
Issue using web interface to "get" local_temperature_calibration from TVR

### ISSUE THREAD

**Issue by maccoylton** [madchicken/homebridge-zigbee-nt#219]
Issue the following using the web interface: {"local_temperature_calibration": ""} 

see the following Error, BTW set for the same attribute works ok

[13/12/2021, 13:58:02] [ZigBee] [TuyaThermostatControl] Update: Office Radiator, local_temperature: 16, running_state: undefined, position: 0, this.state {
  local_temperature: 16,
  current_heating_setpoint: 21,
  preset: 'manual',
  away_mode: 'OFF',
  position: 0,
  system_mode: 'heat',
  force: 'open',
  local_temperature_calibration: 0
} [Function: supports]
[13/12/2021, 13:58:02] [ZigBee] [TuyaThermostatControl] Office Radiator Update CurrentTemperature
[13/12/2021, 13:58:02] [ZigBee] [TuyaThermostatControl] Office Radiator Update TargetTemperature
[13/12/2021, 13:58:02] [ZigBee] [TuyaThermostatControl] Office Radiator Update CurrentHeatingCoolingState with position
[13/12/2021, 13:58:04] [ZigBee] Reading KEY 'local_temperature_calibration' from 'Office Radiator'
[13/12/2021, 13:58:04] [ZigBee] Reading 'local_temperature_calibration' for 'Office Radiator' failed: 'TypeError: converter.convertGet is not a function'
[13/12/2021, 13:58:04] [ZigBee] TypeError: converter.convertGet is not a function
    at ZigBeeClient.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/src/zigbee/zig-bee-client.ts:159:52)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/homebridge-zigbee-nt/dist/zigbee/zig-bee-client.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/homebridge-zigbee-nt/dist/zigbee/zig-bee-client.js:4:12)
    at ZigBeeClient.readDeviceState (/usr/lib/node_modules/homebridge-zigbee-nt/dist/zigbee/zig-bee-client.js:109:16)
    at ZigBeeClient.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/src/zigbee/zig-bee-client.ts:482:17)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/homebridge-zigbee-nt/dist/zigbee/zig-bee-client.js:8:71
    at new Promise (<anonymous>)

**Comment by madchicken** [comment]
See my comment here https://github.com/madchicken/homebridge-zigbee-nt/issues/210#issuecomment-993270559
