### ISSUE TITLE
Endless crash loop with Cskyzk e27 zigbee bulbs

### ISSUE THREAD

**Issue by bgewehr** [madchicken/homebridge-zigbee-nt#222]
Great plugin, thank you for the excellent work!

These bulbs cause the plugin to crash and loop endlessly:
https://www.amazon.de/dp/B09KGQ3HH1?ref_=pe_27091401_487187591_302_E_DDE_dt_1

In this case, how to remove the breaking item from the setup to get back to normal activity?

```
[1/1/2022, 8:09:20 PM] [ZigBee] Initializing ZigBee controller on port /dev/ttyACM0 and channels 11, 25 (pan ID 65534)
[1/1/2022, 8:09:21 PM] [ZigBee] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Function.open (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/controller/database.ts:19:35)
    at Controller.start (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/controller/controller.ts:116:34)
    at ZigBeeController.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/src/zigbee/zigBee-controller.ts:97:25)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/homebridge-zigbee-nt/dist/zigbee/zigBee-controller.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/homebridge-zigbee-nt/dist/zigbee/zigBee-controller.js:4:12)
    at ZigBeeController.start (/usr/lib/node_modules/homebridge-zigbee-nt/dist/zigbee/zigBee-controller.js:98:16)
    at ZigBeeClient.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/src/zigbee/zig-bee-client.ts:70:27)
[1/1/2022, 8:09:21 PM] [ZigBee] Retrying connect to hardware
[1/1/2022, 8:09:26 PM] [ZigBee] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
```
Can I add the bulbs to the database for them to work properly? They were previously successfully paired with IKEA Tradfri Gateway - but no homekit that way, so I started to build a generic homebridge gateway with a CC2531 ZigBee USB-Stick (from here: https://www.amazon.de/dp/B07T3GM28F/ref=pe_27091401_487024491_TE_item).

1) how to remove or fix the crash loop?
2) how to add the bulbs correctly to the setup?

**Comment by bgewehr** [comment]
Turned out that zigbee.db was missing a closing } at the end. How can I help to find the reason for this?

**Comment by bgewehr** [comment]
Got continued problems with that device:

```
[1/2/2022, 5:47:57 AM] TypeError: Cannot read properties of undefined (reading 'debug')
    at clampColorTemp (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman-converters/lib/light.js:76:16)
    at Object.syncColorState (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman-converters/lib/color.js:734:37)
    at Object.convert (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman-converters/converters/fromZigbee.js:603:51)
    at /usr/lib/node_modules/homebridge-zigbee-nt/src/zigbee/zig-bee-client.ts:127:37
    at Array.forEach (<anonymous>)
    at ZigBeeClient.decodeMessage (/usr/lib/node_modules/homebridge-zigbee-nt/src/zigbee/zig-bee-client.ts:123:18)
    at ZigbeeNTHomebridgePlatform.handleZigBeeMessage (/usr/lib/node_modules/homebridge-zigbee-nt/src/platform.ts:414:19)
    at Controller.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/src/platform.ts:124:71)
    at Controller.emit (node:events:390:28)
    at Controller.onZclOrRawData (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/controller/controller.ts:686:18)
[1/2/2022, 5:47:57 AM] Got SIGTERM, shutting down Homebridge...
[1/2/2022, 5:47:58 AM] [ZigBee] Stopping zigbee service
[1/2/2022, 5:47:58 AM] [ZigBee] Zigbee: disabling joining new devices.
```

Again in an endless loop...

**Comment by bgewehr** [comment]
Deleted zigbee.db. Starting from scratch...

**Comment by bgewehr** [comment]
Just for further information:
All devices reset, paired, working.

Again, this happens:

```
[1/2/2022, 6:17:55 AM] Homebridge v1.3.9 (HAP v0.9.8) (Homebridge 132C) is running on port 51919.
[1/2/2022, 6:17:59 AM] [ZigBee] Successfully started ZigBee service
[1/2/2022, 6:17:59 AM] [ZigBee] ZigBee platform initialized @ 0x00124b001cdd29ce
[1/2/2022, 6:17:59 AM] [ZigBee] Reuse accessory from cache with uuid 6895c160-ba25-497f-b805-38071c751c56 and name zigbee:permit-join
[1/2/2022, 6:17:59 AM] [ZigBee] Zigbee: disabling joining new devices.
[1/2/2022, 6:17:59 AM] [ZigBee] PermitJoin accessory successfully registered
[1/2/2022, 6:17:59 AM] [ZigBee] Reuse accessory from cache with uuid 4994893c-ea77-4292-a4ad-09e1f36f7099 and name zigbee:touchlink
[1/2/2022, 6:17:59 AM] [ZigBee] TouchLink accessory successfully registered
[1/2/2022, 6:17:59 AM] [ZigBee] Initializing ZigBee device: 0x00158d00046206b9 - FL 120 C - innr
[1/2/2022, 6:17:59 AM] [ZigBee] Reuse accessory from cache with uuid 59d09f88-5eb6-4f54-bb33-3b2461db87c0 and name 0x00158d00046206b9
[1/2/2022, 6:17:59 AM] [ZigBee] preferAutoDiscover is true: guessing device from zigbee definition
[1/2/2022, 6:17:59 AM] [ZigBee] Registered device: 0x00158d00046206b9 innr FL 120 C
[1/2/2022, 6:17:59 AM] [ZigBee] Mounting device 0x00158d00046206b9...
[1/2/2022, 6:17:59 AM] [ZigBee] Device 0x00158d00046206b9 is a router, install ping
[1/2/2022, 6:17:59 AM] [ZigBee] Initializing ZigBee device: 0x00124b0022d2e249 - ZB-CL01 - eWeLight
[1/2/2022, 6:17:59 AM] [ZigBee] Reuse accessory from cache with uuid cc5ed5ec-6d3b-4612-b4d2-f67f4c2b71dd and name 0x00124b0022d2e249
[1/2/2022, 6:17:59 AM] [ZigBee] preferAutoDiscover is true: guessing device from zigbee definition
[1/2/2022, 6:17:59 AM] [ZigBee] Registered device: 0x00124b0022d2e249 eWeLight ZB-CL01
[1/2/2022, 6:17:59 AM] [ZigBee] Mounting device 0x00124b0022d2e249...
[1/2/2022, 6:17:59 AM] [ZigBee] Device 0x00124b0022d2e249 is a router, install ping
[Sun Jan 02 2022] [ZigBee-UI] Starting WEB UI on port 9000, host is set to 0.0.0.0
[Sun Jan 02 2022] [ZigBee-UI] WebSocket server started @ null
[Sun Jan 02 2022] [ZigBee-UI] WEB UI Listening on port 9000
[1/2/2022, 6:17:59 AM] [ZigBee] Device 0x00158d00046206b9 successfully configured on attempt 1!
[1/2/2022, 6:18:00 AM] [ZigBee] Device 0x00124b0022d2e249 successfully configured on attempt 1!
[1/2/2022, 6:19:45 AM] [ZigBee] Writing 'color' to '0x00158d00046206b9' failed with converter color, color_temp, color_temp_percent: 'Error: Command 0x00158d00046206b9/1 lightingColorCtrl.moveToColor({"transtime":0,"colorx":26836,"colory":16091}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 37336 - 1 - 91 - 768 - 11 after 10000ms)'
[1/2/2022, 6:20:08 AM] [ZigBee] Writing 'color' to '0x00158d00046206b9' failed with converter color, color_temp, color_temp_percent: 'Error: Command 0x00158d00046206b9/1 lightingColorCtrl.moveToColor({"transtime":0,"colorx":32209,"colory":16260}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 37336 - 1 - 92 - 768 - 11 after 10000ms)'
[1/2/2022, 6:20:50 AM] [ZigBee] Writing 'color' to '0x00158d00046206b9' failed with converter color, color_temp, color_temp_percent: 'Error: Command 0x00158d00046206b9/1 lightingColorCtrl.moveToColor({"transtime":0,"colorx":32209,"colory":16260}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 37336 - 1 - 119 - 768 - 11 after 10000ms)'
[1/2/2022, 6:21:14 AM] [ZigBee] Writing 'color' to '0x00158d00046206b9' failed with converter color, color_temp, color_temp_percent: 'Error: Command 0x00158d00046206b9/1 lightingColorCtrl.moveToColor({"transtime":0,"colorx":32209,"colory":16260}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 37336 - 1 - 120 - 768 - 11 after 10000ms)'
```

**Comment by madchicken** [comment]
@bgewehr Sorry, I was out and I did not check this project in the last 2 weeks. It seems the converter (the function that is used to get/set values from/to the device) is failing with a timeout (connection issue?).
The whole logic is handled by the zigbee library, not by the plugin itself.
Just to be sure, the device failing is this one, correct? https://www.zigbee2mqtt.io/devices/FL_120_C.html

**Comment by madchicken** [comment]
I'll close this since it seems a filesystem problem. Feel free to reopen if it is still happening

**Comment by madchicken** [comment]
Then you need to open a bug in the herdsman lib, because it's the one handling the read and write of the database file.
The repo URL is https://github.com/Koenkk/zigbee-herdsman
