### ISSUE TITLE
Error occurred when adding some new devices, then all of paired devices were unpaired (or being accidentally removed)

### ISSUE THREAD

**Issue by Nyaacinth** [madchicken/homebridge-zigbee-nt#237]
Logs:
```
[23/04/2022, 18:26:51] [ZigBee] Registered device: 0x00158d00039e3b44 LUMI lumi.plug
[23/04/2022, 18:26:51] [ZigBee] Mounting device 0x00158d00039e3b44...
[23/04/2022, 18:26:51] [ZigBee] Device 0x00158d00039e3b44 is a router, install ping
[23/04/2022, 18:26:51] [ZigBee] No need to configure device 0x00158d00039e3b44
[23/04/2022, 18:26:51] [ZigBee] No need to configure device 0x00158d00039e3b44
[23/04/2022, 18:26:51] [ZigBee] No need to configure device 0x00158d00039e3b44
[23/04/2022, 18:26:52] [ZigBee] No need to configure device 0x00158d00039e3b44
[23/04/2022, 18:26:52] Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:7:13
    at OutletServiceBuilder.<anonymous> (/usr/local/lib/node_modules/homebridge-zigbee-nt/src/builders/outlet-service-builder.ts:49:9)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-zigbee-nt/dist/builders/outlet-service-builder.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge-zigbee-nt/dist/builders/outlet-service-builder.js:4:12)
    at On.<anonymous> (/usr/local/lib/node_modules/homebridge-zigbee-nt/src/builders/outlet-service-builder.ts:47:87)
    at On.emit (node:events:532:35)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1592:14
    at new Promise (<anonymous>)
```

**Comment by madchicken** [comment]
This is totally unexpected. Could you please enable debug from the Homebridge UI settings and retry? I need more information to understand what happened

**Comment by Nyaacinth** [comment]
```
[24/04/2022, 14:52:28] [ZigBee] Zigbee: allowing new devices to join.
[24/04/2022, 14:52:38] [ZigBee] Accepting joining whitelisted device '0x00158d00039e3b44'
[24/04/2022, 14:52:38] [ZigBee] Device joined, Adding 0x00158d00039e3b44 (undefined - undefined)
[24/04/2022, 14:52:38] [ZigBee] Interview progress started for device 0x00158d00039e3b44
[24/04/2022, 14:52:39] [ZigBee] Device announce: 0x00158d00039e3b44 (LUMI - lumi.plug)
[24/04/2022, 14:52:39] [ZigBee] Not initializing device 0x00158d00039e3b44: interview process still not completed
[24/04/2022, 14:52:39] [ZigBee] Successfully interviewed device: LUMI - lumi.plug
[24/04/2022, 14:52:40] [ZigBee] Initializing ZigBee device: 0x00158d00039e3b44 - lumi.plug - LUMI
[24/04/2022, 14:52:40] [ZigBee] Registering new accessory with uuid c5656cf8-c2f9-4119-96b7-eda62b4dba14 and name 0x00158d00039e3b44
[24/04/2022, 14:52:40] [ZigBee] Registered device: 0x00158d00039e3b44 LUMI lumi.plug
[24/04/2022, 14:52:40] [ZigBee] Mounting device 0x00158d00039e3b44...
[24/04/2022, 14:52:40] [ZigBee] Device 0x00158d00039e3b44 is a router, install ping
[24/04/2022, 14:52:40] [ZigBee] No need to configure device 0x00158d00039e3b44
[24/04/2022, 14:52:40] [homebridge-zigbee-nt] This plugin generated a warning from the characteristic 'Status Low Battery': Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.. See https://git.io/JtMGR for more info.
[24/04/2022, 14:52:40] [homebridge-zigbee-nt] This plugin generated a warning from the characteristic 'Status Tampered': Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.. See https://git.io/JtMGR for more info.
[24/04/2022, 14:52:40] [homebridge-zigbee-nt] This plugin generated a warning from the characteristic 'In Use': Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.. See https://git.io/JtMGR for more info.
[24/04/2022, 14:52:40] [ZigBee] No need to configure device 0x00158d00039e3b44
[24/04/2022, 14:52:41] [ZigBee] Initializing ZigBee device: 0x00158d00039e3b44 - lumi.plug - LUMI
[24/04/2022, 14:52:41] [ZigBee] Reuse accessory from cache with uuid c5656cf8-c2f9-4119-96b7-eda62b4dba14 and name 0x00158d00039e3b44
[24/04/2022, 14:52:41] [ZigBee] Registered device: 0x00158d00039e3b44 LUMI lumi.plug
[24/04/2022, 14:52:41] [ZigBee] Mounting device 0x00158d00039e3b44...
[24/04/2022, 14:52:41] [ZigBee] Device 0x00158d00039e3b44 is a router, install ping
[24/04/2022, 14:52:41] [ZigBee] No need to configure device 0x00158d00039e3b44
[24/04/2022, 14:52:41] [ZigBee] No need to configure device 0x00158d00039e3b44
[24/04/2022, 14:52:41] [ZigBee] No need to configure device 0x00158d00039e3b44
[24/04/2022, 14:52:41] Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:7:13
    at OutletServiceBuilder.<anonymous> (/usr/local/lib/node_modules/homebridge-zigbee-nt/src/builders/outlet-service-builder.ts:49:9)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-zigbee-nt/dist/builders/outlet-service-builder.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge-zigbee-nt/dist/builders/outlet-service-builder.js:4:12)
    at On.<anonymous> (/usr/local/lib/node_modules/homebridge-zigbee-nt/src/builders/outlet-service-builder.ts:47:87)
    at On.emit (node:events:532:35)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1592:14
    at new Promise (<anonymous>)
[24/04/2022, 14:52:41] Got SIGTERM, shutting down Homebridge...
[24/04/2022, 14:52:41] [ZigBee] Stopping zigbee service
[24/04/2022, 14:52:41] [ZigBee] Zigbee: disabling joining new devices.
[24/04/2022, 14:52:41] [ZigBee] No need to configure device 0x00158d00039e3b44
[24/04/2022, 14:52:41] [ZigBee] No need to configure device 0x00158d00039e3b44
[24/04/2022, 14:52:42] [ZigBee] Stopping http server
[24/04/2022, 14:52:42] [ZigBee] Successfully stopped ZigBee service
[24/04/2022, 14:52:46] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[24/04/2022, 14:52:51] [HB Supervisor] Restarting Homebridge...
```
Retried and this is the full log, I will open the debug options and try again. Thanks for response!

**Comment by Nyaacinth** [comment]
I found that when the debug mode enabled, this device seems be successfully added...
![2jowO.png](https://s1.328888.xyz/2022/04/24/2jowO.png)
Then, should I try it again?

**Comment by Nyaacinth** [comment]
After that, I added my all devices without any issue. Seems turning on debug mode solved this problem...

**Comment by madchicken** [comment]
Closing the issue for now. Feel free to reopen it if this problem occurs again
