### ISSUE TITLE
ERROR serialport (DS120J and CC2531)

### ISSUE THREAD

**Issue by ABRT29** [madchicken/homebridge-zigbee-nt#248]
hello, I have this error that appears, I try to build serialport but nothing works... do you have a solution? I want to use a CC2531 key on a Synology DS120J NAS with Homebridge

`ERROR LOADING PLUGIN homebridge-zigbee-nt:
[7/21/2022, 3:49:35 PM] Error: Could not locate the bindings file. Tried:
 → /volume1/homebridge/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/build/bindings.node
 → /volume1/homebridge/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/build/Debug/bindings.node
 → /volume1/homebridge/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/build/Release/bindings.node
 → /volume1/homebridge/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/out/Debug/bindings.node
 → /volume1/homebridge/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/Debug/bindings.node
 → /volume1/homebridge/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/out/Release/bindings.node
 → /volume1/homebridge/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/Release/bindings.node
 → /volume1/homebridge/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/build/default/bindings.node
 → /volume1/homebridge/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/compiled/16.16.0/linux/arm64/bindings.node
 → /volume1/homebridge/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/addon-build/release/install-root/bindings.node
 → /volume1/homebridge/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/addon-build/debug/install-root/bindings.node
 → /volume1/homebridge/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/addon-build/default/install-root/bindings.node
 → /volume1/homebridge/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/lib/binding/node-v93-linux-arm64/bindings.node
    at bindings (/volume1/homebridge/node_modules/homebridge-zigbee-nt/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/volume1/homebridge/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/lib/linux.js:2:36)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/volume1/homebridge/node_modules/homebridge-zigbee-nt/node_modules/@serialport/bindings/lib/index.js:14:22)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)`

**Comment by madchicken** [comment]
This seems more a problem of compilation...is this error showing up during the installation of the plugin? Which step did you execute?
