### ISSUE TITLE
Unable to find Zigbee Port

### ISSUE THREAD

**Issue by remibou78** [madchicken/homebridge-zigbee-nt#265]
Hello,

I've this error after a reboot `[26/06/2023, 15:10:51] Error: Unable to find ZigBee port
    at /usr/lib/node_modules/homebridge-zigbee-nt/src/utils/find-serial-port.ts:13:9
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/homebridge-zigbee-nt/dist/utils/find-serial-port.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[26/06/2023, 15:10:51] Got SIGTERM, shutting down Homebridge...
[26/06/2023, 15:10:51] [ZigBee] Stopping zigbee service
[26/06/2023, 15:10:51] [ZigBee] Zigbee: disabling joining new devices.
[26/06/2023, 15:10:51] [ZigBee] Error while stopping ZigBee service TypeError: Cannot read properties of null (reading 'permitJoin')
    at ZigBeeController.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/src/zigbee/zigBee-controller.ts:132:25)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/homebridge-zigbee-nt/dist/zigbee/zigBee-controller.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/homebridge-zigbee-nt/dist/zigbee/zigBee-controller.js:4:12)
    at ZigBeeController.permitJoin (/usr/lib/node_modules/homebridge-zigbee-nt/dist/zigbee/zigBee-controller.js:127:16)
    at ZigBeeController.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/src/zigbee/zigBee-controller.ts:113:16)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/homebridge-zigbee-nt/dist/zigbee/zigBee-controller.js:8:71
    at new Promise (<anonymous>)`

Could you help me ? 

Regards

**Comment by madchicken** [comment]
Hey, sorry for the late response...what kind of USB antenna are you using? Is it compatible with the ones listed on https://github.com/Koenkk/zigbee-herdsman ?
