### ISSUE TITLE
Aqara QBKG38LM can't connect

### ISSUE THREAD

**Issue by dejwiczech** [madchicken/homebridge-zigbee-nt#292]
Hi all,

trying to connect Aqara QBKG38LM switch but after joining zigbee network homebridge-zigbee-nt start to restarting homebridge continously. Here is log:

```
[17/10/2024, 01:11:10] [ZigBee] Cluster with name 'aqaraOpple' does not exist
[Thu Oct 17 2024] [ZigBee-UI] Request: http://homebridge:9000/coordinator
[Thu Oct 17 2024] [ZigBee-UI] Request: http://homebridge:9000/index.a6fec750.js
[Thu Oct 17 2024] [ZigBee-UI] Request: http://homebridge:9000/api/coordinator
[Thu Oct 17 2024] [ZigBee-UI] Request: http://homebridge:9000/api/devices
[Thu Oct 17 2024] [ZigBee-UI] Request: http://homebridge:9000/api/devices/0x54ef441000d68c89
[Thu Oct 17 2024] [ZigBee-UI] Request: http://homebridge:9000/api/devices/0x54ef441000d68c89/checkForUpdates
zh:controller:endpoint: CommandResponse 0x54ef441000d68c89/1 genOta.imageNotify({"payloadType":0,"queryJitter":100}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false,"sendWhen":"immediate"})
zh:zstack: sendZclFrameToEndpointInternal 0x54ef441000d68c89:31756/1 (0,0,1)
zh:zstack:znp: SREQ: --> AF - dataRequest - {"dstaddr":31756,"destendpoint":1,"srcendpoint":1,"clusterid":25,"transid":2,"options":0,"radius":30,"len":5,"data":{"type":"Buffer","data":[25,3,0,0,100]}}
zh:zstack:unpi:writer: --> frame [254,15,36,1,12,124,1,1,25,0,2,0,30,5,25,3,0,0,100,36]
zh:zstack:unpi:parser: <-- [254,1,100,1,0,100]
zh:zstack:unpi:parser: --- parseNext [254,1,100,1,0,100]
zh:zstack:unpi:parser: --> parsed 1 - 3 - 4 - 1 - [0] - 100
zh:zstack:znp: SRSP: <-- AF - dataRequest - {"status":0}
zh:zstack:unpi:parser: --- parseNext []
zh:zstack:unpi:parser: <-- [254,3,68,128,0,1,2,196]
zh:zstack:unpi:parser: --- parseNext [254,3,68,128,0,1,2,196]
zh:zstack:unpi:parser: --> parsed 3 - 2 - 4 - 128 - [0,1,2] - 196
zh:zstack:znp: AREQ: <-- AF - dataConfirm - {"status":0,"endpoint":1,"transid":2}
zh:zstack:unpi:parser: --- parseNext []
zh:zstack:unpi:parser: <-- [254,32,68,129,0,0,25,0,12,124,1,1,0,68,0,250,46,107,0,0,12,1,174,1,0,95,17,8,26,23,0,0,0,12,124,29,243]
zh:zstack:unpi:parser: --- parseNext [254,32,68,129,0,0,25,0,12,124,1,1,0,68,0,250,46,107,0,0,12,1,174,1,0,95,17,8,26,23,0,0,0,12,124,29,243]
zh:zstack:unpi:parser: --> parsed 32 - 2 - 4 - 129 - [0,0,25,0,12,124,1,1,0,68,0,250,46,107,0,0,12,1,174,1,0,95,17,8,26,23,0,0,0,12,124,29] - 243
zh:zstack:znp: AREQ: <-- AF - incomingMsg - {"groupid":0,"clusterid":25,"srcaddr":31756,"srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"linkquality":68,"securityuse":0,"timestamp":7024378,"transseqnumber":0,"len":12,"data":{"type":"Buffer","data":[1,174,1,0,95,17,8,26,23,0,0,0]}}
zh:controller: Received payload: clusterID=25, address=31756, groupID=0, endpoint=1, destinationEndpoint=1, wasBroadcast=false, linkQuality=68, frame={"header":{"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":0,"disableDefaultResponse":false,"reservedBits":0},"manufacturerCode":null,"transactionSequenceNumber":174,"commandIdentifier":1},"payload":{"fieldControl":0,"manufacturerCode":4447,"imageType":6664,"fileVersion":23},"command":{"ID":1,"response":2,"parameters":[{"name":"fieldControl","type":32},{"name":"manufacturerCode","type":33},{"name":"imageType","type":33},{"name":"fileVersion","type":35}],"name":"queryNextImageRequest"}}
zh:zstack:unpi:parser: --- parseNext []
zh:controller:database: Writing database to '/var/lib/homebridge/zigBee.db'
Error: Cluster with name 'aqaraOpple' does not exist
    at getClusterDefinition (/var/lib/homebridge/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/zspec/zcl/utils.ts:157:19)
    at Object.getCluster (/var/lib/homebridge/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/zspec/zcl/utils.ts:277:29)
    at Endpoint.getCluster (/var/lib/homebridge/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:804:26)
    at Endpoint.write (/var/lib/homebridge/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:372:30)
    at Object.configure (/var/lib/homebridge/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman-converters/src/devices/xiaomi.ts:3106:41)
    at ConfigurableAccessory.<anonymous> (/var/lib/homebridge/node_modules/homebridge-zigbee-nt/src/accessories/zig-bee-accessory.ts:175:28)
    at Generator.next (<anonymous>)
    at /var/lib/homebridge/node_modules/homebridge-zigbee-nt/dist/accessories/zig-bee-accessory.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/var/lib/homebridge/node_modules/homebridge-zigbee-nt/dist/accessories/zig-bee-accessory.js:4:12)
[17/10/2024, 01:11:44] [ZigBee] Child bridge process ended
```

Using zstack CC2351

Any Ideas?

Thanks and best regards

**Comment by dejwiczech** [comment]
Here is joining log:

```
Initializing ZigBee device: 0x54ef441000d68c89 - lumi.switch.b2lc04 - LUMI
[16/10/2024, 23:43:39] [ZigBee] Registering new accessory with uuid c126f6d3-922a-4253-83c8-fa1dfeec3d0d and name 0x54ef441000d68c89
[16/10/2024, 23:43:39] [ZigBee] Registered device: 0x54ef441000d68c89 LUMI lumi.switch.b2lc04
[16/10/2024, 23:43:39] [ZigBee] Mounting device 0x54ef441000d68c89...
[16/10/2024, 23:43:39] [ZigBee] Configuring device 0x54ef441000d68c89
zh:controller:database: Writing database to '/var/lib/homebridge/zigBee.db'
zh:zstack:unpi:parser: <-- [254,34,68,129,0,0,6,0,3,168,2,1,0,23,0,231,116,110,0,0,14,24,146,10,0,0,16,0,245,0,35,0,255,255,2,3,168,29,95]
zh:zstack:unpi:parser: --- parseNext [254,34,68,129,0,0,6,0,3,168,2,1,0,23,0,231,116,110,0,0,14,24,146,10,0,0,16,0,245,0,35,0,255,255,2,3,168,29,95]
zh:zstack:unpi:parser: --> parsed 34 - 2 - 4 - 129 - [0,0,6,0,3,168,2,1,0,23,0,231,116,110,0,0,14,24,146,10,0,0,16,0,245,0,35,0,255,255,2,3,168,29] - 95
zh:zstack:znp: AREQ: <-- AF - incomingMsg - {"groupid":0,"clusterid":6,"srcaddr":43011,"srcendpoint":2,"dstendpoint":1,"wasbroadcast":0,"linkquality":23,"securityuse":0,"timestamp":7238887,"transseqnumber":0,"len":14,"data":{"type":"Buffer","data":[24,146,10,0,0,16,0,245,0,35,0,255,255,2]}}
zh:controller: Received payload: clusterID=6, address=43011, groupID=0, endpoint=2, destinationEndpoint=1, wasBroadcast=false, linkQuality=23, frame={"header":{"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":true,"reservedBits":0},"manufacturerCode":null,"transactionSequenceNumber":146,"commandIdentifier":10},"payload":[{"attrId":0,"dataType":16,"attrData":0},{"attrId":245,"dataType":35,"attrData":50331392}],"command":{"ID":10,"name":"report","parameters":[{"name":"attrId","type":33},{"name":"dataType","type":32},{"name":"attrData","type":1000}]}}
zh:zstack:unpi:parser: --- parseNext []
zh:controller:database: Writing database to '/var/lib/homebridge/zigBee.db'
Error: Cluster with name 'aqaraOpple' does not exist
    at getClusterDefinition (/var/lib/homebridge/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/zspec/zcl/utils.ts:157:19)
    at Object.getCluster (/var/lib/homebridge/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/zspec/zcl/utils.ts:277:29)
    at Endpoint.getCluster (/var/lib/homebridge/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:804:26)
    at Endpoint.write (/var/lib/homebridge/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:372:30)
    at Object.configure (/var/lib/homebridge/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman-converters/src/devices/xiaomi.ts:3091:41)
    at ConfigurableAccessory.<anonymous> (/var/lib/homebridge/node_modules/homebridge-zigbee-nt/src/accessories/zig-bee-accessory.ts:175:28)
    at Generator.next (<anonymous>)
    at /var/lib/homebridge/node_modules/homebridge-zigbee-nt/dist/accessories/zig-bee-accessory.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/var/lib/homebridge/node_modules/homebridge-zigbee-nt/dist/accessories/zig-bee-accessory.js:4:12)
```
