### ISSUE TITLE
Router Polling Error 

### ISSUE THREAD

**Issue by EdwardChamberlain** [madchicken/homebridge-zigbee-nt#59]
Running v1.0.8 I get the error below on repeat. 

```
[12/27/2020, 20:01:32] [ZigBee] [RouterPolling] ping device error: 0x086bd7fffe3521ed IKEA of Sweden: TRADFRI control outlet DataConfirmError: Read 0x086bd7fffe3521ed/1 genBasic(["zclVersion"], {"timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'MAC no ack' (233))
    at ZStackAdapter.<anonymous> (/usr/local/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:367:23)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58) {
  code: 233
}
```

**Comment by madchicken** [comment]
From this error, it seems your TRADFRI control outlet is offline. Does it work?
You can disable router polling from the config now.

**Comment by EdwardChamberlain** [comment]
It was a socket controlling our Christmas lights that had been unplugged! Plugging it back in has made it work again. I get irregular disconnections now on another socket but I suspect it is due to a poor connection so will try to improve the mesh coverage.
