### ISSUE TITLE
tuya thermostat radiator value issue "'TypeError: Cannot read property 'state' of undefined"

### ISSUE THREAD

**Issue by maccoylton** [madchicken/homebridge-zigbee-nt#83]
Testing out the pull request for the tuya thermostat radiator valve and got an error as below,  any pointers on how to drug? 

[18/01/2021, 12:48:11] [ZigBee] translateToSystemMode(0): off
[18/01/2021, 12:48:12] [ZigBee] Writing 'system_mode' to '0x5c0272fffec8901f' failed: 'TypeError: Cannot read property 'state' of undefined

**Comment by madchicken** [comment]
Do you have a stack trace for this error?

**Comment by maccoylton** [comment]
new to the environment, how would I do that?

**Comment by madchicken** [comment]
In logs. Don't you see any other information when the error show up?

**Comment by maccoylton** [comment]
Reset everything and fetched the pull request not getting this error:- 

Initializing ZigBee controller on port /dev/ttyACM0 and channels 11, 25
(node:21209) UnhandledPromiseRejectionWarning: Error: PanID must have a value of 0x0001 (1) - 0xFFFE (65534), got 65535.
    at new Controller (/usr/lib/node_modules/homebridge-zigbee-nt/node_modules/zigbee-herdsman/src/controller/controller.ts:98:19)
    at ZigBeeController.init (/usr/lib/node_modules/homebridge-zigbee-nt/src/zigbee/zigBee-controller.ts:73:21)
    at ZigBeeClient.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/src/zigbee/zig-bee-client.ts:61:17)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/homebridge-zigbee-nt/dist/zigbee/zig-bee-client.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21209) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21209) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:21209) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/home/homebridge/.lgtv2'
(node:21209) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[22/01/2021, 21:30:41] [webostv] [Conser

**Comment by madchicken** [comment]
Closing for lack of information about the problem
